name: format

on:
  push:
    branches:
      - "dev"
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  stylua_check:
    name: "Stylua - Format check"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: run stylua
        uses: JohnnyMorganz/stylua-action@1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --check .
          version: "0.13.1"
